apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "196"
    deployment_number: $127
    deployment_tag: 129-20220302T1642-V2TestCreation
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":80,"protocol":"HTTP","serviceName":"staging:tests-service","ingressName":"staging:ingress-alb-resource","hostname":"staginggoldcms.studyiq.com","path":"/*","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"188","deployment_number":"$127","deployment_tag":"129-20220302T1642-V2TestCreation","timestamp":"20220302T170205"},"creationTimestamp":null,"generation":2,"labels":{"app":"userauth:53-k8s-store-adda247-dev-16-05_07-42
    timestamp: 20220302T170205
  creationTimestamp: "2022-03-24T11:58:23Z"
  generation: 95729
  labels:
    app: userauth:53-k8s-store-adda247-dev-16-05_07-42
    app.kubernetes.io/instance: adda-dev-deployment
  name: userauth:53-k8s-store-adda247-dev-16-05_07-42
  namespace: dev
  resourceVersion: "25361016"
  uid: 7825be12-1752-4e95-8c60-e9be89d9b69b
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: userauth:53-k8s-store-adda247-dev-16-05_07-42
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 5%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-02-09T15:55:42Z"
      creationTimestamp: null
      labels:
        app: userauth:53-k8s-store-adda247-dev-16-05_07-42
    spec:
      affinity: {}
      containers:
      - env:
        - name: coin.data.migration.cron
          value: "0 36 16 * * ?"
        - name: coin.data.migration.cron.active
          value: "false"
        - name: coin.expiration.cron
          value: "0 52 16 * * ?"
        - name: coin.expiration.cron.active
          value: "true"
        - name: coin.notification.delete.cron
          value: "0 30 9 ? * *"
        - name: coin.notification.delete.cron.active
          value: "true"
        - name: coin.notification.delete.cron.before.days
          value: "5"
        - name: coin.process.notification.cron
          value: "0 27 17 ? * *"
        - name: coin.process.notification.cron.active
          value: "true"
        - name: coin.process.notification.cron.limit
          value: "1000"
        - name: coin.process.notification.cron.retry-count
          value: "1"
        - name: coin.process.notification.wait.msec
          value: "10000"
        - name: com.sun.net.ssl.enableECC
          value: "false"
        - name: deployment
          value: staging
        - name: discourse.api.jwt.token
          value: eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJzaGFua2FyLnlhZGF2QGFkZGEyNDcuY29tIiwiaWF0IjoxNTY2MzY1MTc3LCJpc3MiOiJhZGRhMjQ3LmNvbSIsIm5hbWUiOiJTaGFua2FyIFlhZGF2In0.-RTEmiFQWotPGA-F9q9gQDxshFx9snMYN_MmyRNI9Xjv3XmR0KyQG8Rhr4iGFfXToDs9B0GBUu_OsdBKxADPrg
        - name: discourse.api.search.url
          value: https://socialsync.adda247.com/users/avatar
        - name: discourse.api.update.profile
          value: https://socialsync.adda247.com/users/avatar
        - name: discourse.request.idle.milisecdiscourse.request.idle.milisec
          value: "4000"
        - name: doubt.api.search.url
          value: https://stagingdoubt.adda247.com/search/query.json
        - name: elastic.apm.application_packages
          value: userapi.adda247.com
        - name: elastic.apm.environment
          value: staging
        - name: elastic.apm.server_url
          value: http://addadash.adda247.in:30202
        - name: elastic.apm.service_name
          value: userauth:53-k8s-store-adda247-dev-16-05_07-42
        - name: logging.config
          value: classpath:logback-staging.xml
        - name: logging.level.in.careerpower
          value: DEBUG
        - name: logging.level.org.springframework.web
          value: INFO
        - name: moengage.app.value
          value: K8GPTWLR90JVA3LUB477MRG7
        - name: moengage.error.from-mail
          value: stagingerrors@adda247.com
        - name: moengage.error.to-mail
          value: stagingerrors@adda247.com
        - name: moengage.push
          value: "true"
        - name: otp.generation.limit
          value: "50"
        - name: spring.profiles.active
          value: staging
        - name: sqs.accessKey
          value: AKIAXES3NEUR56X6U3HR
        - name: sqs.secretKey
          value: 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
        - name: sqs.sociallcsuser.queue.url
          value: https://sqs.ap-south-1.amazonaws.com/490891715875/user-auth.fifo
        - name: superuser.password
          value: amitpundir
        - name: usablecoin.maxvalue
          value: "10000"
        - name: usablecoin.percent
          value: "1"
        - name: user.discourse.registration
          value: https://socialsync.adda247.com/users
        - name: user.doubt.registration
          value: https://stagingdoubt.adda247.com/users
        - name: cloud.aws.credentials.instanceProfile
          value: "false"
        - name: cloud.aws.stack.auto
          value: "false"
        image: 490891715875.dkr.ecr.us-east-1.amazonaws.com/userauth:53-k8s-store-adda247-dev-16-05_07-42
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthCheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        name: userauth:53-k8s-store-adda247-dev-16-05_07-42
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthCheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-04-28T07:26:22Z"
    lastUpdateTime: "2022-05-11T08:59:37Z"
    message: ReplicaSet "userauth:53-k8s-store-adda247-dev-16-05_07-42
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-11T11:04:32Z"
    lastUpdateTime: "2022-05-11T11:04:32Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 95729
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 2
