apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "196"
    deployment_number: $127
    deployment_tag: 129-20220302T1642-V2TestCreation
    field.cattle.io/publicEndpoints: '[{"addresses":[""],"port":80,"protocol":"HTTP","serviceName":"staging:tests-service","ingressName":"staging:ingress-alb-resource","hostname":"staginggoldcms.studyiq.com","path":"/*","allNodes":false}]'
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"188","deployment_number":"$127","deployment_tag":"129-20220302T1642-V2TestCreation","timestamp":"20220302T170205"},"creationTimestamp":null,"generation":2,"labels":{"app":"videoserver-dev","app.kubernetes.io/instance":"adda-dev-deployment","velero.io/backup-name":"staging","velero.io/restore-name":"staging-20220324115750"},"managedFields":[{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:deployment.kubernetes.io/revision":{},"f:deployment_number":{},"f:deployment_tag":{},"f:kubectl.kubernetes.io/last-applied-configuration":{},"f:timestamp":{}},"f:labels":{".":{},"f:app":{},"f:velero.io/backup-name":{},"f:velero.io/restore-name":{}}},"f:spec":{"f:progressDeadlineSeconds":{},"f:replicas":{},"f:revisionHistoryLimit":{},"f:selector":{},"f:strategy":{"f:rollingUpdate":{".":{},"f:maxSurge":{},"f:maxUnavailable":{}},"f:type":{}},"f:template":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/restartedAt":{}},"f:labels":{".":{},"f:app":{}}},"f:spec":{"f:affinity":{},"f:containers":{"k:{\"name\":\"videoserver-dev\"}":{".":{},"f:env":{".":{},"k:{\"name\":\"ELASTIC_APM_ENVIRONMENT\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ELASTIC_APM_SERVER_URLS\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"ELASTIC_APM_SERVICE_NAME\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"eureka.instance.preferIpAddress\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"spring.cloud.config.server.git.search-paths\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"spring.cloud.config.uri\"}":{".":{},"f:name":{},"f:value":{}},"k:{\"name\":\"spring.profiles.active\"}":{".":{},"f:name":{},"f:value":{}}},"f:image":{},"f:imagePullPolicy":{},"f:lifecycle":{".":{},"f:preStop":{".":{},"f:exec":{".":{},"f:command":{}}}},"f:livenessProbe":{".":{},"f:failureThreshold":{},"f:httpGet":{".":{},"f:path":{},"f:port":{},"f:scheme":{}},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:name":{},"f:ports":{".":{},"k:{\"containerPort\":8100,\"protocol\":\"TCP\"}":{".":{},"f:containerPort":{},"f:name":{},"f:protocol":{}}},"f:readinessProbe":{".":{},"f:failureThreshold":{},"f:httpGet":{".":{},"f:path":{},"f:port":{},"f:scheme":{}},"f:initialDelaySeconds":{},"f:periodSeconds":{},"f:successThreshold":{},"f:timeoutSeconds":{}},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}},"f:requests":{".":{},"f:cpu":{},"f:memory":{}}},"f:terminationMessagePath":{},"f:terminationMessagePolicy":{}}},"f:dnsPolicy":{},"f:imagePullSecrets":{".":{},"k:{\"name\":\"nexus-regcred\"}":{".":{},"f:name":{}}},"f:restartPolicy":{},"f:schedulerName":{},"f:securityContext":{},"f:terminationGracePeriodSeconds":{}}}}},"manager":"velero-server","operation":"Update","time":"2022-03-24T11:58:23Z"},{"apiVersion":"apps/v1","fieldsType":"FieldsV1","fieldsV1":{"f:status":{"f:conditions":{".":{},"k:{\"type\":\"Available\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}},"k:{\"type\":\"Progressing\"}":{".":{},"f:lastTransitionTime":{},"f:lastUpdateTime":{},"f:message":{},"f:reason":{},"f:status":{},"f:type":{}}},"f:observedGeneration":{}}},"manager":"kube-controller-manager","operation":"Update","time":"2022-03-24T12:00:21Z"}],"name":"videoserver-dev","namespace":"dev"},"spec":{"progressDeadlineSeconds":600,"replicas":2,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"videoserver-dev"}},"strategy":{"rollingUpdate":{"maxSurge":"100%","maxUnavailable":"5%"},"type":"RollingUpdate"},"template":{"metadata":{"annotations":{"kubectl.kubernetes.io/restartedAt":"2022-02-09T15:55:42Z"},"creationTimestamp":null,"labels":{"app":"videoserver-dev"}},"spec":{"affinity":{},"containers":[{"env":[{"name":"spring.profiles.active","value":"dev"},{"name":"spring.cloud.config.server.git.search-paths","value":"StudyIQ-Config/dev"},{"name":"spring.cloud.config.uri","value":"http://configservice-staging-main:8012"},{"name":"eureka.instance.preferIpAddress","value":"true"},{"name":"ELASTIC_APM_SERVICE_NAME","value":"tests-service-staging"},{"name":"ELASTIC_APM_SERVER_URLS","value":"http://apm-server.logging:8200"},{"name":"ELASTIC_APM_ENVIRONMENT","value":"staging"}],"image":"748804974185.dkr.ecr.ap-south-1.amazonaws.com/tests-service:11May141607-staging-master","imagePullPolicy":"Always","livenessProbe":{"failureThreshold":30,"httpGet":{"path":"/test-ws/v1/health/live","port":8086,"scheme":"HTTP"},"initialDelaySeconds":300,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":30},"name":"videoserver-dev","ports":[{"containerPort":8086,"name":"http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":30,"httpGet":{"path":"/test-ws/v1/health/ready","port":8086,"scheme":"HTTP"},"initialDelaySeconds":300,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":30},"resources":{"limits":{"cpu":"500m","memory":"1Gi"},"requests":{"cpu":"500m","memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File"}],"dnsPolicy":"ClusterFirst","imagePullSecrets":[{"name":"nexus-regcred"}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30}}},"status":{"conditions":[{"lastTransitionTime":"2022-03-24T12:00:20Z","lastUpdateTime":"2022-03-24T12:00:20Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2022-03-24T11:58:38Z","lastUpdateTime":"2022-03-24T12:00:21Z","message":"ReplicaSet \"videoserver-dev-7fc8d77ddf\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":2}}
    timestamp: 20220302T170205
  creationTimestamp: "2022-03-24T11:58:23Z"
  generation: 95729
  labels:
    app: videoserver-dev
    app.kubernetes.io/instance: adda-dev-deployment
  name: videoserver-dev
  namespace: dev
  resourceVersion: "25361016"
  uid: 7825be12-1752-4e95-8c60-e9be89d9b69b
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: videoserver-dev
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 5%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2022-02-09T15:55:42Z"
      creationTimestamp: null
      labels:
        app: videoserver-dev
    spec:
      affinity: {}
      containers:
      - env:
        - name: couchbase.skip.singleview.code
          value: "false"
        - name: disable.video.logs
          value: "0"
        - name: drm.authxml.non.persistent.expiry
          value: "1800"
        - name: drm.authxml.persistent.expiry
          value: "1800"
        - name: elastic.apm.environment
          value: staging
        - name: elastic.apm.server_url
          value: http://addadash.adda247.in:30202
        - name: elastic.apm.service_name
          value: videoservernew
        - name: logging.config
          value: classpath:logback-staging.xml
        - name: logging.level.in.careerpower
          value: "DEBUG"
        - name: secure.token.validity
          value: "300"
        - name: storefront.packageValidateUri
          value: "https://stagingstore2.adda247.com/api/v1/package/validate"
        - name: switch.cdn
          value: "false"
        - name: user.range.end
          value: "1"
        - name: user.range.start
          value: "1"
        - name: video.httpservice.url
          value: https://stagingstore.adda247.com
        image: 490891715875.dkr.ecr.us-east-1.amazonaws.com/videoserver:v1
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthCheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        name: videoserver-dev
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 30
          httpGet:
            path: /healthCheck
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 30
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: nexus-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2022-04-28T07:26:22Z"
    lastUpdateTime: "2022-05-11T08:59:37Z"
    message: ReplicaSet "videoserver-dev-666c46fcdf" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-05-11T11:04:32Z"
    lastUpdateTime: "2022-05-11T11:04:32Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 95729
  readyReplicas: 1
  replicas: 2
  unavailableReplicas: 1
  updatedReplicas: 2