apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: Preprod-Adda
  region: us-east-1

vpc:
  id: "vpc-08bf906c"
  cidr: "172.31.0.0/16"
  subnets:
    private:
      us-east-1d:
          id: "subnet-0651066f1cbb6b7f3"
          cidr: "172.31.112.0/20"
      us-east-1a:
          id: "subnet-074b1a1b23c639c86"
          cidr: "172.31.96.0/20"
    public:
      us-east-1a:
          id: "subnet-30d27b68"
          cidr: "172.31.16.0/20"
      us-east-1d:
          id: "subnet-2fb02659"
          cidr: "172.31.0.0/20"
nodeGroups:
  - name: Preprod-Adda-Worker2
    minSize: 3
    maxSize: 50
    desiredCapacity: 3
    instancesDistribution:
      instanceTypes: [t3.medium , t3.micro, t2.small, t2.micro, t3.small, t2.medium, t3a.large, t4g.large, t2.large]
      onDemandBaseCapacity: 0
      onDemandPercentageAboveBaseCapacity: 0
      spotAllocationStrategy: capacity-optimized
    labels:
      role: Workers
      lifecycle: Ec2Spot
      aws.amazon.com/spot: "true"
    volumeSize: 20
    privateNetworking: true
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ['sg-0dee6b2cf92438f45', 'sg-08cae75386d12399e']
    ssh:
      allow: true
      publicKeyName: 'preprod-adda'
    tags:
      'environment:Prod': 'Preprod-Adda'
      'k8s.io/cluster-autoscaler/node-template/label/lifecycle': 'Ec2Spot'
      'k8s.io/cluster-autoscaler/node-template/label/aws.amazon.com/spot': 'true'
    iam:
      withAddonPolicies:
        autoScaler: true
