apiVersion: apps/v1
kind: Deployment
metadata:
  name: $appname
  labels:
    app: $appname
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
  revisionHistoryLimit: 2
  paused: false
  minReadySeconds: 10
  selector:
    matchLabels:
      app: $appname
  template:
    metadata:
      name: $appname
      labels:
        app: $appname
      containers:
        - name: $appname
          image: 490891715875.dkr.ecr.us-east-1.amazonaws.com/$appname:"$envName-$branch-$BUILD_NUMBER"
          ports:
            - containerPort:  8080
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /v1/healthCheck
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 2
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /v1/healthCheck
              port: 8080
            initialDelaySeconds: 300
            periodSeconds: 5
          resources:
            limits:
              cpu: "1000m"
              memory: "1000Mi"
            requests:
              cpu: "400m"
              memory: "500Mi"
      nodeSelector:
         role: Workers
