---
apiVersion: v1
kind: Service
metadata:
  name: $appname
  labels:
      app: $appname
spec:
  type: NodePort
  selector:
    app: $appname
  ports:
  - protocol: TCP
    name: web
    port: 8080
    targetPort: 8080
